# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem 'rspec'
gem 'cucumber'
gem 'capybara', '<3.1.1'
gem 'selenium-webdriver'
gem 'require_all'
gem 'site_prism'
gem 'pry'
gem 'syntax'
